version: "3.8"

services:
  assistant:
    image: agentcontainers/assistant
    build:
      context: images/assistant
      args:
        GIT_DELTA_VERSION: "0.18.2"
        ZSH_IN_DOCKER_VERSION: "1.2.0"
    env_file:
      - .secrets

  shim:
    image: agentcontainers/shim
    build:
      context: .
      dockerfile: Dockerfile.shim
    volumes:
      - .:/usr/src/shim
    working_dir: /usr/src/shim
