version: "3.8"

services:
  claude:
    image: agentcontainers/claude
    build:
      context: images/claude
      args:
        GIT_DELTA_VERSION: "0.18.2"
        ZSH_IN_DOCKER_VERSION: "1.2.0"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
      CLAUDE_CONFIG_DIR: "/home/node/.claude"
      POWERLEVEL9K_DISABLE_GITSTATUS: "true"
